- id: go-vet
  name: go-vet
  entry: go-vet.sh
  language: script
  files: \.go$
  pass_filenames: false
- id: gofmt
  name: gofmt
  entry: gofmt.sh
  language: script
  files: \.go$
- id: ginkgo
  name: ginkgo
  entry: ginkgo.sh
  language: script
  files: \.go$
  pass_filenames: false
